name: Dynamic_TopK_Ranking_Service_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
    - name: Build and run the tests
      run: |
        chmod +x ./mvnw
        ./mvnw clean
        ./mvnw test
    - name: Build and run the app
      run: |
        chmod +x ./mvnw
        ./mvnw clean
        ./mvnw spring-boot:run
